blueprint:
  name: Snake Enclosure - Ensure Heat/Light State on HA Boot
  description: Automation to ensure the lights and thermostat preset is set correctly based on the scheduled day start and night start.
  domain: automation
  input:
    day_time_start:
      name: Day Time Start Time
      selector:
        entity:
          domain:
            - input_datetime
    night_time_start:
      name: Night Time Start Time
      selector:
        entity:
          domain:
            - input_datetime
    thermostat_selection:
      name: Enclosure Thermostat
      selector:
        entity:
          domain:
            - climate
          multiple: false
    lights_selection:
      name: Enclosure Lights
      selector:
        entity:
          domain:
            - switch
            - input_boolean
            #- light
          multiple: true

variables:
  day_time_start: !input "day_time_start"
  night_time_start: !input "night_time_start"
  thermostat_selection: !input "thermostat_selection"
  lights_selection: !input "lights_selection"

alias: <EnclosureName> - Ensure Heat/Light State on HA Boot
#description: Use the helper field to turn the Day Light Bulb *ON* at the scheduled time.

trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - choose:
      - conditions: #DAY TIME
          - condition: time
            after: !input day_time_start
            before: !input night_time_start
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: comfort
            entity_id: !input thermostat_selection
          - service: climate.set_preset_mode
            data:
              hvac_mode: heat
            entity_id: !input thermostat_selection
          - service: homeassistant.turn_on
            target:
              entity_id: '{{ expand(lights_selection) | selectattr("entity_id", "!=", trigger.entity_id) | map(attribute="entity_id") | list }}'
      - conditions: # NIGHT TIME
          - condition: time
            after: !input night_time_start
            before: !input day_time_start
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: eco
            entity_id: !input thermostat_selection
          - service: climate.set_preset_mode
            data:
              hvac_mode: heat
            entity_id: !input thermostat_selection
          - service: homeassistant.turn_off
            target:
              entity_id: '{{ expand(lights_selection) | selectattr("entity_id", "!=", trigger.entity_id) | map(attribute="entity_id") | list }}'

    default: []
mode: single
