blueprint:
  name: Snake Enclosure - Light Switch - Scheduled On/Off
  description: Automation for turning on and off light switches at the scheduled day start and night start.
  domain: automation
  input:
    day_time_start:
      name: Day Time Start Time
      selector:
        entity:
          domain:
            - input_datetime
    night_time_start:
      name: Night Time Start Time
      selector:
        entity:
          domain:
            - input_datetime

    lights_selection:
      name: Enclosure Lights
      selector:
        entity:
          domain:
            - switch
            #- light
          multiple: true

#    enclosure_name:
#      name: Enclosure Name

#    light_type_name:
#      name: Type of the lights (UV, Heat, Grow, etc)

variables:
  day_time_start: !input "day_time_start"
  night_time_start: !input "night_time_start"
  lights_selection: !input "lights_selection"
  #enclosure_name: !input "enclosure_name"

alias: <EnclosureName> - <LightType> Light Switch - Scheduled On/Off
description: Use the helper field to turn the Day Light Bulb *ON* at the scheduled time.

trigger:
  - platform: time
    at: !input day_time_start
    id: "day_start"
  - platform: time
    at: !input night_time_start
    id: "night_start"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "day_start"

        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: '{{ expand(lights_selection) | selectattr("entity_id", "!=", trigger.entity_id) | map(attribute="entity_id") | list }}'

      - conditions:
          - condition: trigger
            id: "night_start"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: '{{ expand(lights_selection) | selectattr("entity_id", "!=", trigger.entity_id) | map(attribute="entity_id") | list }}'
    default: []

mode: single
