blueprint:
  name: Snake Enclosure - Heater Thermostat - Preset Scheduled Switching
  description: Automation for changing the thermostat preset at the scheduled day start and night start.
  domain: automation
  input:
    day_time_start:
      name: Day Time Start Time
      selector:
        entity:
          domain:
            - input_datetime
    night_time_start:
      name: Night Time Start Time
      selector:
        entity:
          domain:
            - input_datetime

    thermostat_selection:
      name: Enclosure Thermostat
      selector:
        entity:
          domain:
            - climate
          multiple: false

variables:
  day_time_start: !input "day_time_start"
  night_time_start: !input "night_time_start"
  thermostat_selection: !input "thermostat_selection"

alias: <EnclosureName> - Heater Thermostat - Preset Scheduled Switching
#description: Use the helper field to turn the Day Light Bulb *ON* at the scheduled time.

trigger:
  - platform: time
    at: !input day_time_start
    id: "day_start"
  - platform: time
    at: !input night_time_start
    id: "night_start"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "day_start"

        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: comfort
            entity_id: !input thermostat_selection
      - conditions:
          - condition: trigger
            id: "night_start"
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: eco
            entity_id: !input thermostat_selection
    default:
      sequence:
        - service: climate.set_preset_mode
          data:
            preset_mode: comfort
          entity_id: !input thermostat_selection
mode: single
